name: NestJS CI

on:
  workflow_call:
    inputs:
      is-test:
        required: false
        default: 'false'
        type: string
      is-e2e-test:
        required: false
        default: 'false'
        type: string
      is-ci:
        required: false
        default: 'false'
        type: string
    secrets:
      PAT:
        required: true

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.PAT }}
      - name: Use Node.js
        if: ${{ inputs['is-ci'] == 'true' }}  # CI 진행 여부
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        if: ${{ inputs['is-ci'] == 'true' }}  # CI 진행 여부
        run: npm ci

      - name: Nest Build
        if: ${{ inputs['is-ci'] == 'true' }}  # CI 진행 여부
        run: npm run build

      - name: Nest Test
        if: ${{ inputs['is-test'] == 'true' && inputs['is-ci'] == 'true' }}  # CI 및 테스트 진행 여부
        run: npm run test