name: NestJS Image Build and Push

on:
  workflow_call:
    secrets:
      PAT:
        required: true

jobs:
  image-build-and-push-linux-amd64:
    runs-on: ubuntu-latest

    steps:
      - name: Convert Repository to Lowercase
        id: repo_to_lower
        run: echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Set Branch Name
        id: branch_name
        run: |
          echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          token: ${{ secrets.PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Project Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          provenance: false
          file: ./Dockerfile
          tags: ghcr.io/${{ env.REPO_NAME }}/api:${{ env.branch_name }}
          cache-from: type=registry,ref=ghcr.io/${{ env.REPO_NAME }}/api-cache:${{ env.branch_name }}
          cache-to: type=registry,ref=ghcr.io/${{ env.REPO_NAME }}/api-cache:${{ env.branch_name }},mode=max
#          cache-from: type=gha
#          cache-to: type=gha,mode=max

      - name: Prisma Migration Deploy Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          provenance: false
          file: ./prisma-migrate-deploy.Dockerfile
          tags: ghcr.io/${{ env.REPO_NAME }}/prisma-migrate-deploy:${{ env.branch_name }}
          cache-from: type=registry,ref=ghcr.io/${{ env.REPO_NAME }}/prisma-migrate-deploy-cache:${{ env.branch_name }}
          cache-to: type=registry,ref=ghcr.io/${{ env.REPO_NAME }}/prisma-migrate-deploy-cache:${{ env.branch_name }},mode=max
#          cache-from: type=gha
#          cache-to: type=gha,mode=max